import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { env } from '../config/env.js';

function payslipDir() {
  const dir = path.join(env.exportFilesDir || path.join(process.cwd(), 'exports'), 'payslips');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function money(pence) {
  return `£${(Number(pence || 0) / 100).toFixed(2)}`;
}

export async function renderPayslipPdf(payslip) {
  const payload = typeof payslip.payload === 'string' ? JSON.parse(payslip.payload) : payslip.payload;
  const filename = `payslip-${payslip.id}.pdf`;
  const absPath = path.join(payslipDir(), filename);
  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48 });
    const out = fs.createWriteStream(absPath);
    out.on('finish', resolve);
    out.on('error', reject);
    doc.pipe(out);
    doc.fontSize(18).text('Lunar Security Payslip', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).text(`Payslip #${payslip.id}`);
    doc.text(`Payroll Run: ${payload.payrollRunId}`);
    doc.text(`User ID: ${payload.userId}`);
    doc.text(`Hours Worked: ${payload.hoursWorked}`);
    doc.moveDown();
    doc.text(`Gross: ${money(payload.grossPence)}`);
    doc.text(`PAYE: ${money(payload.payePence)}`);
    doc.text(`NI Employee: ${money(payload.niEmployeePence)}`);
    doc.text(`Pension Employee: ${money(payload.meta?.pensionEmployeePence)}`);
    doc.text(`Net: ${money(payload.netPence)}`);
    doc.moveDown();
    doc.fontSize(9).text('Generated by Lunar Security. Verify payroll configuration before production use.');
    doc.end();
  });
  return {
    absPath,
    relPath: path.relative(process.cwd(), absPath),
    mime: 'application/pdf',
  };
}

export async function ensurePayslipPdf(pool, payslipId) {
  const [[payslip]] = await pool.query(`SELECT * FROM payslips WHERE id = ?`, [payslipId]);
  if (!payslip) return null;
  if (payslip.file_path && fs.existsSync(path.isAbsolute(payslip.file_path) ? payslip.file_path : path.join(process.cwd(), payslip.file_path))) {
    return payslip;
  }
  const rendered = await renderPayslipPdf(payslip);
  await pool.query(`UPDATE payslips SET file_path = ?, file_mime = ? WHERE id = ?`, [
    rendered.relPath,
    rendered.mime,
    payslipId,
  ]);
  return { ...payslip, file_path: rendered.relPath, file_mime: rendered.mime };
}
